name: Ezy SQB Build & Packaging

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/EzySQB/EzySQB.csproj
    - name: Build
      run: dotnet build --no-restore ./src/EzySQB/EzySQB.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal ./tests/EzySQB.Tests/EzySQB.Tests.csproj